In [1]:
x = [1, 2, 3, 4]

In [2]:
x[0]

1

In [3]:
x[0:1]

[1]

In [4]:
x[0:2]

[1, 2]

In [5]:
x[2:3]

[3]

In [6]:
x[2:2]

[]

In [7]:
x[2:1]

[]

In [8]:
x[4]

IndexError: list index out of range

In [9]:
x[4:3]

[]

In [10]:
x[4:]

[]

In [11]:
import torch

In [32]:
x = torch.tensor([1, 2, 3, 4])

In [52]:
x = x.view(1, -1)

In [53]:
x

tensor([[1, 2, 3, 4]])

In [57]:
x[[0], [1]]

tensor([2])

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [59]:
x[4:]

tensor([], size=(0, 4), dtype=torch.int64)

In [64]:
x[0, [0]]

tensor([1])

In [65]:
y = torch.cat((x[0, [0]], x[0, [2]]), dim=-1)

In [66]:
y

tensor([1, 3])

In [67]:
x[:, 0:2]

tensor([[1, 2]])

In [69]:
x[:, 2:]

tensor([[3, 4]])

In [70]:
x.shape

torch.Size([1, 4])

In [73]:
y = torch.cat((x[:, 0:2], x[:, 2:]), dim=0)

In [74]:
y

tensor([[1, 2],
        [3, 4]])

In [75]:
x = x.view(-1, 1)

In [76]:
x

tensor([[1],
        [2],
        [3],
        [4]])

In [81]:
y = torch.cat((x, x), dim=1)

In [82]:
y

tensor([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [84]:
z = torch.tensor([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

In [85]:
z

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [87]:
z[:, [0]]

tensor([[ 1],
        [ 5],
        [ 9],
        [13]])

In [88]:
y = torch.cat((z[:, [0]], z[:, 2:]), dim=1)

In [89]:
y

tensor([[ 1,  3,  4],
        [ 5,  7,  8],
        [ 9, 11, 12],
        [13, 15, 16]])

In [90]:
y = torch.cat((z[:, [0]], z[:, 4:]), dim=1)

In [91]:
y

tensor([[ 1],
        [ 5],
        [ 9],
        [13]])

In [93]:
dict_trial = {'bleep': 'blop', 'ping':'pong'}

In [94]:
dict_trial['baa']

KeyError: 'baa'

In [99]:
if dict_trial['baa', 'default'] == 'pong':
    print('Here')
else:
    print('not here')

KeyError: ('baa', 'default')

In [100]:
if dict_trial.get('baa', None):
    print('Here')
else:
    print('not here')

not here


In [101]:
x = torch.tensor([1,-1])

In [102]:
x

tensor([ 1, -1])

In [103]:
y = abs(x)

In [104]:
y

tensor([1, 1])

In [105]:
x = [1, -1]

In [110]:
y = [abs(value) for value in x]

In [111]:
y

[1, 1]

In [113]:
print('try \'quotes\'')

try 'quotes'


In [114]:
list(range(5))

[0, 1, 2, 3, 4]

In [116]:
y = torch.tensor([[1, 2], [3, 4], [5, 6]])

In [117]:
y

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [118]:
z = y[:, 1]

In [119]:
z

tensor([2, 4, 6])

In [120]:
z=y[:, [1]]

In [121]:
z

tensor([[2],
        [4],
        [6]])

In [124]:
z=y[:, 1:2]

In [125]:
z

tensor([[2],
        [4],
        [6]])

In [129]:
if 0:
    print('here')
else:
    print('not here')

not here


In [132]:
import numpy as np

In [133]:
x = np.array([2, 2])

In [134]:
x

array([2, 2])

In [135]:
y = x**2

In [136]:
y

array([4, 4])

In [137]:
x += 1

In [138]:
x

array([3, 3])

In [139]:
y

array([4, 4])

In [140]:
y=x

In [141]:
y

array([3, 3])

In [142]:
x += 2

In [143]:
y

array([5, 5])

In [144]:
z = torch.tensor([1, 1, 0, 1, 1, 0])

In [145]:
torch.nonzero(z)

tensor([[0],
        [1],
        [3],
        [4]])

In [146]:
torch.nonzero(z)[:, 0]

tensor([0, 1, 3, 4])

In [147]:
x = [1, 2, 3, 4]

In [148]:
x.remove(2)

In [149]:
x

[1, 3, 4]

In [150]:
x.remove(5)

ValueError: list.remove(x): x not in list

In [151]:
y = torch.tensor([1, 2, 3, 4])

In [152]:
y.remove(1)

AttributeError: 'Tensor' object has no attribute 'remove'

In [154]:
if 2 in y:
    print('Here')
else:
    print('not here')

Here


In [155]:
len(y)

4

In [158]:
a = {'Input_Type': 'Strai'}

In [159]:
if a.get('Input_Type', None) == ('Strain' or 'Stress'):
    print('Here')
else:
    print('not here')

not here


In [161]:
x = range(1,0)

In [163]:
list(x)

[]

In [165]:
import sympy as sym

In [247]:
def Eval_Array_From_Expression(Input_Value_Array, Symbol_Variable, Symbolic_Expression):
    
    try:
        raise
        Eval_Func = sp.lambdify(Symbol_Variable, Symbolic_Expression)
        Result_Array = Eval_Func(Input_Value_Array)
        if len(Result_Array) != len(Input_Value_Array):
            raise
    except:
        Result_Array = np.array([])
        print(Result_Array)
        print(Input_Value_Array)
        print(type(Input_Value_Array))
        for Input_Value in Input_Value_Array:
            print(Input_Value)
            print(type(Input_Value))
            Result_Array = np.append(Result_Array, float(Symbolic_Expression.evalf(subs={Symbol_Variable: Input_Value})))
        
        print(type(Input_Value_Array))
        print(type(Result_Array))
        print(type(Result_Array[0]))
        if type(Input_Value_Array) is torch.Tensor:
            print('took bad method and hit numpy place')
            print(Result_Array)
            Result_Array = torch.tensor(Result_Array)
            print(Result_Array)
    
    return Result_Array

In [231]:
t = sym.symbols('t', real=True)

In [253]:
a = torch.tensor([0.1], requires_grad=True)

In [254]:
b = a*2

In [255]:
a

tensor([0.1000], requires_grad=True)

In [256]:
b

tensor([0.2000], grad_fn=<MulBackward0>)

In [258]:
x = Eval_Array_From_Expression(b, t, sym.sin(t))

[]
tensor([0.2000], grad_fn=<MulBackward0>)
<class 'torch.Tensor'>
tensor(0.2000, grad_fn=<SelectBackward>)
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
took bad method and hit numpy place
[0.19866933]
tensor([0.1987], dtype=torch.float64)


In [217]:
x

array([[0.84147098]])

In [218]:
b = torch.tensor(x)

In [219]:
b

tensor([[0.8415]], dtype=torch.float64)

In [222]:
x = Eval_Array_From_Expression(torch.tensor([[1.]]), t, sym.sin(t))

good method


In [223]:
x

tensor([[0.8415]])

In [224]:
c = torch.tensor(x)

/Users/alexanderbrandon-bravo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


In [225]:
c

tensor([[0.8415]])

In [175]:
y = torch.tensor([1,2,3,4,5], dtype=torch.float32, requires_grad=True)

In [176]:
y

tensor([1., 2., 3., 4., 5.], requires_grad=True)

In [177]:
x = Eval_Array_From_Expression(y, t, sym.sin(t))

In [178]:
x

array([0.841470984807897, 0.909297426825682, 0.141120008059867,
       -0.756802495307928, -0.958924274663138], dtype=object)

In [179]:
y

tensor([1., 2., 3., 4., 5.], requires_grad=True)

In [180]:
x = Eval_Array_From_Expression(y.detach(), t, sym.sin(t))

In [181]:
y

tensor([1., 2., 3., 4., 5.], requires_grad=True)

In [182]:
x

array([0.841470984807897, 0.909297426825682, 0.141120008059867,
       -0.756802495307928, -0.958924274663138], dtype=object)

In [205]:
print(type(np.array([1,2,3,4,5])))

<class 'numpy.ndarray'>


In [226]:
print(type(torch.tensor([1,2,3,4,5])))

<class 'torch.Tensor'>


In [227]:
x = np.array([])

In [228]:
x

array([], dtype=float64)

In [229]:
print(x)

[]


In [236]:
help(sym.evalf)

Help on module sympy.core.evalf in sympy.core:

NAME
    sympy.core.evalf

DESCRIPTION
    Adaptive numerical evaluation of SymPy expressions, using mpmath
    for mathematical functions.

CLASSES
    builtins.ArithmeticError(builtins.Exception)
        PrecisionExhausted
    builtins.object
        EvalfMixin
    
    class EvalfMixin(builtins.object)
     |  Mixin class adding evalf capabililty.
     |  
     |  Methods defined here:
     |  
     |  evalf(self, n=15, subs=None, maxn=100, chop=False, strict=False, quad=None, verbose=False)
     |      Evaluate the given formula to an accuracy of n digits.
     |      Optional keyword arguments:
     |      
     |          subs=<dict>
     |              Substitute numerical values for symbols, e.g.
     |              subs={x:3, y:1+pi}. The substitutions must be given as a
     |              dictionary.
     |      
     |          maxn=<integer>
     |              Allow a maximum temporary working precision of maxn digits
     |

In [389]:
def Eval_Array_From_Expression(Input_Value_Array, Symbol_Variable, Symbolic_Expression):
    
    try:
        raise
        Eval_Func = sym.lambdify(Symbol_Variable, Symbolic_Expression)
        Result_Array = Eval_Func(Input_Value_Array)
        if len(Result_Array) != len(Input_Value_Array):
            raise
    except:
        Result_Array = np.array([])
        # Both arrays and tensors have a method flatten() meaning by chance the same statement works for both.
        for Input_Value in Input_Value_Array.flatten():
            Result_Array = np.append(Result_Array, float(Symbolic_Expression.evalf(subs={Symbol_Variable: Input_Value})))
        
        Result_Array = Result_Array.reshape(Input_Value_Array.shape)
        
        if type(Input_Value_Array) is torch.Tensor:
            Result_Array = torch.tensor(Result_Array)
    
    return Result_Array

In [402]:
x = torch.tensor([1,2,3,4]).view((-1,1))

In [403]:
x[:]

tensor([[1],
        [2],
        [3],
        [4]])

In [404]:
y = Eval_Array_From_Expression(x, t, sym.sin(t))

In [405]:
y

tensor([[ 0.8415],
        [ 0.9093],
        [ 0.1411],
        [-0.7568]], dtype=torch.float64)

In [407]:
list(range(1, 5))

[1, 2, 3, 4]

In [410]:
import torch

In [418]:
def check_need_overide(sparsity_mask_trial, original_diff_order):
    Index_Gap = original_diff_order+1
    
    #First check zeroth and first derivatives are present. In no model is there ever the situation where either of these should  be removed, except for a single spring
    for coeff_index in [0, Index_Gap-1, Index_Gap]:
        if not coeff_index in sparsity_mask_trial:
            return True
    
    #Next check if these 3 are the only remaining, in which case no more can be removed
    if len(sparsity_mask_trial) == 3:
        return False
    
    #Next check if all pairs are like
    for coeff_index in range(1, original_diff_order):
        if (coeff_index in sparsity_mask_trial) != (coeff_index+Index_Gap in sparsity_mask_trial):
            return True
    
    #Next check that no derivatives skipped
    Expected_State = False
    for coeff_index in range(1, original_diff_order):
        if (coeff_index in sparsity_mask_trial) == Expected_State:
            if Expected_State == True:
                return True
            
            Expected_State = True
                
    return False

In [422]:
check_need_overide(torch.tensor([0, 2, 3, 4]), 3)

1 in
2 in
3 in
3 out


True

In [423]:
x = [(1,2,3), (4,5,6)]

In [424]:
x

[(1, 2, 3), (4, 5, 6)]

In [425]:
y = zip(x)

In [426]:
y

In [427]:
print(y)

In [448]:
a = [10,40]
b = [20,50]
c = [30,60]

In [449]:
z = zip(a, b, c)

In [450]:
z

In [451]:
d, e, f = zip(*z)

In [452]:
d

(10, 40)

In [443]:
l1, l2 = print(*z)
print(*z)

(10, 20, 30) (40, 50, 60)


TypeError: cannot unpack non-iterable NoneType object

In [437]:
d = zip(list(z))

In [438]:
print(*d)

In [455]:
a = zip(*[1,2,3])

TypeError: zip argument #1 must support iteration

In [454]:
print(*a)

(1, 4, 7) (2, 5, 8) (3, 6, 9)


In [456]:
print(*zip([1],[2],[3]))

(1, 2, 3)


In [458]:
r = zip(*[(1,2,3)])

In [459]:
r

In [460]:
print(*r)

(1,) (2,) (3,)


In [472]:
t = zip((1,2,3), (4,5,6))

In [473]:
a, b, c = t

In [474]:
a = list(a)

In [475]:
a

[1, 4]

In [476]:
import sympy as sym

In [477]:
E_0, E_1, E_2, Eta_1, Eta_2 = sym.symbols('E_0,E_1,E_2,Eta_1,Eta_2', real=True, positive=True)

In [512]:
Eps, Sig = sym.symbols('epsilon,sigma', real=True)

In [513]:
Eps

epsilon

In [488]:
t = sym.symbols('t', real=True)

In [498]:
LHS = E_1*(E_2*Eps + Eta_2*sym.Derivative(Eps, t)) + Eta_1*sym.Derivative(E_2*Eps + Eta_2*sym.Derivative(Eps, t), t)

In [499]:
LHS

E_1*(E_2*Eps + Eta_2*Derivative(Eps, t)) + Eta_1*Derivative(E_2*Eps + Eta_2*Derivative(Eps, t), t)

In [491]:
sym.Derivative(Eps, t)

Derivative(Eps, t)

In [493]:
RHS = Sig*(1/E_0 + 1/(E_1 + Eta_1*sym.Derivative(1, t)) + 1/(E_2 + Eta_2*sym.Derivative(1, t)))

In [494]:
LHS

Eps

In [495]:
RHS

Sig*(1/(E_2 + Eta_2*Derivative(1, t)) + 1/(E_1 + Eta_1*Derivative(1, t)) + 1/E_0)

In [500]:
dt=sym.symbols('dt')

In [502]:
expr = dt*dt*dt*Sig

In [503]:
expr

Sig*dt**3

In [506]:
expr = expr.subs((Sig*dt**3), sym.Derivative(Sig, t,t,t))

This seems good but remember, when looping need to START from teh HIGHEST deriv otherwise dt\*Sig will be replaced even when dt^2\*Sig is present etc

In [507]:
expr

Derivative(Sig, (t, 3))

In [480]:
x = torch.tensor([1.,2.,3.,4.,5.], requires_grad=True)

In [481]:
x

tensor([1., 2., 3., 4., 5.], requires_grad=True)

In [482]:
with torch.no_grad():
    y = 2*x

In [483]:
y

tensor([ 2.,  4.,  6.,  8., 10.])

In [484]:
print(y)

tensor([ 2.,  4.,  6.,  8., 10.])


In [485]:
print(x)

tensor([1., 2., 3., 4., 5.], requires_grad=True)


In [1]:
import sympy as sym
import torch

In [2]:
def kelvin_sym_sum(order):
    
    E_Syms = [sym.symbols('E_'+str(Branch_Index), real=True, negative=False) for Branch_Index in range(1, order+1)]
    Eta_Syms = [sym.symbols('eta_'+str(Branch_Index), real=True, negative=False) for Branch_Index in range(1, order+1)]
    
    all_syms = E_Syms + Eta_Syms
    
    dt = sym.symbols('dt')
    
    Expression = sym.S(0)
    for Branch_Index in range(len(E_Syms)):
        Expression += 1/(E_Syms[Branch_Index] + Eta_Syms[Branch_Index]*dt)
        
    return Expression, all_syms

In [3]:
def kelvin_coeff_expressions(coeff_count):
    
    order = coeff_count // 2
    
    eps, sig = sym.symbols('epsilon,sigma', real=True)
    E_0 = sym.symbols('E_0', real=True, negative=False)
    
    #Create and organise Kelvin general equation
    summation, model_params_list = kelvin_sym_sum(order)
    model_params_list = [E_0] + model_params_list
    RHS = (1/E_0 + summation)*sig
    RHS = sym.together(RHS)
    RHS, denom = sym.fraction(RHS)
    
    full_expression = RHS - eps*denom
    
    #find coeffs - prep
    expanded = sym.expand(full_expression)
    dt = sym.symbols('dt')
    
    #Strain coeffs
    coeff_expressions_list = [-expanded.coeff(eps, 1).coeff(dt, 0)]
    for strain_order in range(2, order+1):
        coeff_expressions_list += [-expanded.coeff(eps, 1).coeff(dt, strain_order)]
        
    #Stress coeffs
    for stress_order in range(order+1):
        coeff_expressions_list += [expanded.coeff(sig, 1).coeff(dt, stress_order)]
    
    return coeff_expressions_list, model_params_list
    

In [4]:
ces, model_params_list = kelvin_coeff_expressions(5)
ces

[E_0*E_1*E_2,
 E_0*eta_1*eta_2,
 E_0*E_1 + E_0*E_2 + E_1*E_2,
 E_0*eta_1 + E_0*eta_2 + E_1*eta_2 + E_2*eta_1,
 eta_1*eta_2]

In [12]:
model_params_list

[E_0, E_1, E_2, eta_1, eta_2]

In [6]:
def equations_with_coeff_results(coeff_expression_list, coeff_value_list):
    
    coeff_equations_list = [coeff_expression - coeff_value for coeff_expression, coeff_value in zip(coeff_expression_list, coeff_value_list)]
    
    return coeff_equations_list

In [9]:
coeff_equations_list = equations_with_coeff_results(ces, torch.tensor([1,10,3,22,10]))
coeff_equations_list

[E_0*E_1*E_2 - 1.0,
 E_0*eta_1*eta_2 - 10.0,
 E_0*E_1 + E_0*E_2 + E_1*E_2 - 3.0,
 E_0*eta_1 + E_0*eta_2 + E_1*eta_2 + E_2*eta_1 - 22.0,
 eta_1*eta_2 - 10.0]

In [11]:
param_solutions_list = sym.solve(coeff_equations_list, model_params_list)
param_solutions_list

[(1.00000000000000,
  1.00000000000000,
  1.00000000000000,
  1.00000000000000,
  10.0000000000000),
 (1.00000000000000,
  1.00000000000000,
  1.00000000000000,
  10.0000000000000,
  1.00000000000000)]

In [3]:
Eps = sym.symbols('epsilon', real=True)
LHS = Eps

In [4]:
Loop_Result, params = kelvin_sym_sum(2)
Loop_Result

1/(E_2 + dt*eta_2) + 1/(E_1 + dt*eta_1)

In [5]:
Sig = sym.symbols('sigma', real=True)
E_0 = sym.symbols('E_0', real=True, negative=False)
RHS = (1/E_0 + Loop_Result)*Sig
RHS

sigma*(1/(E_2 + dt*eta_2) + 1/(E_1 + dt*eta_1) + 1/E_0)

In [6]:
RHS = sym.together(RHS)
RHS

sigma*(E_0*(E_1 + dt*eta_1) + E_0*(E_2 + dt*eta_2) + (E_1 + dt*eta_1)*(E_2 + dt*eta_2))/(E_0*(E_1 + dt*eta_1)*(E_2 + dt*eta_2))

In [7]:
RHS, Denom = sym.fraction(RHS)
RHS

sigma*(E_0*(E_1 + dt*eta_1) + E_0*(E_2 + dt*eta_2) + (E_1 + dt*eta_1)*(E_2 + dt*eta_2))

In [8]:
Denom

E_0*(E_1 + dt*eta_1)*(E_2 + dt*eta_2)

In [9]:
LHS = LHS*Denom
LHS

E_0*epsilon*(E_1 + dt*eta_1)*(E_2 + dt*eta_2)

In [10]:
Final_Expr = RHS - LHS
Final_Expr

-E_0*epsilon*(E_1 + dt*eta_1)*(E_2 + dt*eta_2) + sigma*(E_0*(E_1 + dt*eta_1) + E_0*(E_2 + dt*eta_2) + (E_1 + dt*eta_1)*(E_2 + dt*eta_2))

In [11]:
expanded = sym.expand(Final_Expr)
expanded

-E_0*E_1*E_2*epsilon - E_0*E_1*dt*epsilon*eta_2 + E_0*E_1*sigma - E_0*E_2*dt*epsilon*eta_1 + E_0*E_2*sigma - E_0*dt**2*epsilon*eta_1*eta_2 + E_0*dt*eta_1*sigma + E_0*dt*eta_2*sigma + E_1*E_2*sigma + E_1*dt*eta_2*sigma + E_2*dt*eta_1*sigma + dt**2*eta_1*eta_2*sigma

In [12]:
dt = sym.symbols('dt')
Strain_t_coeff_expr = -expanded.coeff(Eps, 1).coeff(dt, 1)
Strain_t_coeff_expr

E_0*E_1*eta_2 + E_0*E_2*eta_1

In [13]:
coeff00 = -expanded.coeff(Eps, 1).coeff(dt, 0) / Strain_t_coeff_expr

In [14]:
coeff00

E_0*E_1*E_2/(E_0*E_1*eta_2 + E_0*E_2*eta_1)

In [16]:
coeff00_simple = sym.simplify(coeff00)
coeff00_simple

E_1*E_2/(E_1*eta_2 + E_2*eta_1)

In [18]:
expanded /= Strain_t_coeff_expr
expanded

(-E_0*E_1*E_2*epsilon - E_0*E_1*dt*epsilon*eta_2 + E_0*E_1*sigma - E_0*E_2*dt*epsilon*eta_1 + E_0*E_2*sigma - E_0*dt**2*epsilon*eta_1*eta_2 + E_0*dt*eta_1*sigma + E_0*dt*eta_2*sigma + E_1*E_2*sigma + E_1*dt*eta_2*sigma + E_2*dt*eta_1*sigma + dt**2*eta_1*eta_2*sigma)/(E_0*E_1*eta_2 + E_0*E_2*eta_1)

In [23]:
new = sym.simplify(expanded)
new

(-E_0*E_1*E_2*epsilon - E_0*E_1*dt*epsilon*eta_2 + E_0*E_1*sigma - E_0*E_2*dt*epsilon*eta_1 + E_0*E_2*sigma - E_0*dt**2*epsilon*eta_1*eta_2 + E_0*dt*eta_1*sigma + E_0*dt*eta_2*sigma + E_1*E_2*sigma + E_1*dt*eta_2*sigma + E_2*dt*eta_1*sigma + dt**2*eta_1*eta_2*sigma)/(E_0*(E_1*eta_2 + E_2*eta_1))

In [19]:
expanded.coeff(Eps, 1).coeff(dt, 0)

0

In [9]:
x=[1,2,3]
y=[4,5,6]
z = x+y
z

[1, 2, 3, 4, 5, 6]

In [10]:
import sympy as sym

In [14]:
x,y,z=sym.symbols('x,y,z')
coeff_expression = x+y
coeff_expression.evalf(subs={x: 1, y: 2, z: 3})

3.00000000000000

In [15]:
x,y,z=sym.symbols('x,y,z')
coeff_expression = x+y
coeff_expression.evalf(subs={x: 1})

x + y

In [18]:
x,y,z=sym.symbols('x,y,z')
coeff_expression = x+y
coeff_expression.subs(zip([x,y,z], [1,2,3]))

3

In [2]:
import torch
import sys

sys.path.append('../')
import Documents.GitHub.DeePyMoD_torch_AlexVersion.src.deepymod_torch.VE_params as VE_params

In [26]:
E_mods = [1,1]
viscs = [20]
coeffs = VE_params.coeffs_from_model_params(E_mods, viscs)
coeffs

[1/20, 1/10, 1]

In [23]:
output = torch.tensor(coeffs, dtype=torch.float32, requires_grad=True)
#output = coeffs
output

tensor([0.0909, 0.9091, 0.2727, 2.0000, 0.9091], requires_grad=True)

In [24]:
VE_params.model_params_from_coeffs(output)

([(1.00000000000000,
   1.00000000993411,
   0.999999900658933,
   1.00000004304780,
   9.99999897347564)],
 [E_0, E_1, E_2, eta_1, eta_2])

In [1]:
import numpy as np
import random as rn

In [3]:
rn.random()

0.6621928620057038

In [4]:
x=np.array([1,2,3])

In [5]:
rn.shuffle(x)

In [6]:
x

array([2, 1, 3])

In [7]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
rn.shuffle(x)

In [10]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
help(rn.shuffle)

Help on method shuffle in module random:

shuffle(x, random=None) method of random.Random instance
    Shuffle list x in place, and return None.
    
    Optional argument random is a 0-argument function returning a
    random float in [0.0, 1.0); if it is the default None, the
    standard random.random will be used.



In [24]:
x=np.array([1,2,3]).reshape(-1,1)

In [25]:
x

array([[1],
       [2],
       [3]])

In [22]:
rn.shuffle(x)

In [23]:
x

array([[1],
       [2],
       [1]])

In [32]:
x=np.array([1,2,3]).reshape(-1,1)
x

array([[1],
       [2],
       [3]])

In [33]:
np.random.shuffle(x)

In [34]:
x

array([[1],
       [3],
       [2]])

In [35]:
x=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
np.random.shuffle(x)
x

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [38]:
help(np.random.permutation)

Help on built-in function permutation:

permutation(...) method of numpy.random.mtrand.RandomState instance
    permutation(x)
    
    Randomly permute a sequence, or return a permuted range.
    
    If `x` is a multi-dimensional array, it is only shuffled along its
    first index.
    
    Parameters
    ----------
    x : int or array_like
        If `x` is an integer, randomly permute ``np.arange(x)``.
        If `x` is an array, make a copy and shuffle the elements
        randomly.
    
    Returns
    -------
    out : ndarray
        Permuted sequence or array range.
    
    
    Examples
    --------
    >>> np.random.permutation(10)
    array([1, 7, 4, 3, 0, 9, 2, 5, 8, 6]) # random
    
    >>> np.random.permutation([1, 4, 9, 12, 15])
    array([15,  1,  9,  4, 12]) # random
    
    >>> arr = np.arange(9).reshape((3, 3))
    >>> np.random.permutation(arr)
    array([[6, 7, 8], # random
           [0, 1, 2],
           [3, 4, 5]])



In [1]:
import torch

In [2]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
50%50

0

In [2]:
import numpy as np

In [3]:
help(np.std)

Help on function std in module numpy:

std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>)
    Compute the standard deviation along the specified axis.
    
    Returns the standard deviation, a measure of the spread of a distribution,
    of the array elements. The standard deviation is computed for the
    flattened array by default, otherwise over the specified axis.
    
    Parameters
    ----------
    a : array_like
        Calculate the standard deviation of these values.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the standard deviation is computed. The
        default is to compute the standard deviation of the flattened array.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a standard deviation is performed over
        multiple axes, instead of a single axis or all the axes as before.
    dtype : dtype, optional
        Type to use in computing the standard deviation. For arrays of
       