# Guide by demonstration of some fetures for saving data and moving it around

Need to run the numpy code a bit later to save the file used to demonstrated the first bit

## Reading files in general

Generally, files are just read into dumb strings. If we want to store this as anything fancy, like a list, we need to use better modules, like the 'csv' module or NumPy, or design our own loops.

Read the whole file and output as a string. The '\n' characters for line endings do seem to have been understood. The 'r' means read only.

In [43]:
filename = "myarray.csv"

with open(filename, 'r') as filehandle:
    filecontent = filehandle.read()
    print (filecontent)

# Births, Deaths, Rebirths
8.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00
8.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00
8.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00
# Bs, Ds, RBs



read line by line. the example explicitely shows the closing of the file, usually handled by 'with'. The edits to a file are neveractually written to the disk until the file is closed apparently (this may be done by leaving a `with` block

In [36]:
filename = "myarray.csv"

# open the file for reading
filehandle = open(filename, 'r')
while True:
    # read a single line
    line = filehandle.readline()
    if not line:
        break
    print(line)

# close the pointer to that file
filehandle.close()

# Births, Deaths, Rebirths

8.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00

8.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00

8.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00

# Bs, Ds, RBs



or, as the with statement handles closing for us.

In [38]:
filename = "myarray.csv"

# open the file for reading
with open(filename, 'r') as filehandle:
    while True:
        # read a single line
        line = filehandle.readline()
        if not line:
            break
        print(line)

# Births, Deaths, Rebirths

8.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00

8.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00

8.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00

# Bs, Ds, RBs



or, as the file is automatically made iterable over its lines

In [39]:
filename = "myarray.csv"

for line in open(filename, 'r'):
    print(line)

# Births, Deaths, Rebirths

8.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00

8.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00

8.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00

# Bs, Ds, RBs



or, automatically taking it line by line and saving the result in a list, use:

In [45]:
filename = "myarray.csv"

with open(filename, 'r') as filehandle:
    filecontent = filehandle.readlines()
    print (filecontent)

['# Births, Deaths, Rebirths\n', '8.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00\n', '8.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00\n', '8.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00\n', '# Bs, Ds, RBs\n']


Pull out a specific line:

In [42]:
filename = "myarray.csv"

# define the line number
line_number = 3

print("line %i of %s is: " % (line_number, filename))

with open(filename, 'r') as filehandle:
    current_line = 1
    for line in filehandle:
        if current_line == line_number:
            print(line)
            break
        current_line += 1

line 3 of myarray.csv is: 
8.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00



## Writing files in General

Opening files with the writable 'w' flag will create a file if none exists in the location specified, or entirelty overwrite if it already exists. Use 'a' to indicate we want to append our input to the file instead.

In [49]:
filehandle = open('helloworld.txt', 'w')
filehandle.write('Hello, World!\n')
filehandle.close()

or

In [56]:
with open('helloworld.txt', 'w') as filehandle:
    filehandle.write('Hello, world - with with!\n')

or, to write lines, line by line, and using each line as a different element of a list:

Note, without the funny business of the list comprehension, the elements of the list would simply by concatenated on a single line.

In [57]:
with open('helloworld.txt', 'w') as filehandle:
    filebuffer = ["a line of text", "another line of text", "a third line"]
    filehandle.writelines("%s\n" % line for line in filebuffer)

Using the append modality

In [58]:
with open('helloworld.txt', 'a') as filehandle:
    filehandle.write('\n' + 'Hello, world!\n')

## Writing and reading NumPy arrays

In [1]:
import numpy as np

In [ ]:
test_array = np.full((3,3), 10)
print(test_array)

The header and footer fields are kind of useless. Just adds comments at the start and end. the comments are recognised by using a # symbol.

In [ ]:
np.savetxt("myarray.csv", test_array, delimiter=',', header='Births, Deaths, Rebirths', footer='Bs, Ds, RBs')

Use '../myarray.csv' for files in the directory above the cwd, and 'test_folder/myarray.csv' for files in a subfolder of the cwd.

In [3]:
test_read = np.loadtxt('myarray.csv', delimiter=',')
print(test_read)

[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


## Managing directories

Getting the CWD

In [2]:
import os

In [25]:
path = os.getcwd()
print ("The current working directory is %s" % path)

The current working directory is /Users/alexanderbrandon-bravo/OneDrive/Documents/Paris - CRI/Early Learning


Changing directory

In [16]:
os.chdir('../')
print(os.getcwd())

/Users/alexanderbrandon-bravo/OneDrive/Documents/Paris - CRI/Early Learning


In [20]:
os.chdir(path)
print(os.getcwd())

/Users/alexanderbrandon-bravo/OneDrive/Documents/Paris - CRI/Early Learning


Careful: Changing directory in a file called by this file changes the CWD of this file.

The code in the called file is


```
import os

print(os.getcwd())

os.chdir(''../../')

print(os.getcwd())
```

Notice the use of `../../` to back up 2 folders.

Below I also demonstrate the syntax for calling a file to be run from an ipython environment like this notebook. The `.py` is optional. Additionally, the `""` are optional in the case that the file being run is already in teh CWD. In the case below, I have taken the file and put it in a subfolder, and so teh `""` are needed to describe the route to the file. Always use `""` not `''` as the latter is not supported on windows.

The `%` indicates this is not actually a python script command, but an IPython console command. This is why the arguements such as `-n` and `-i` are specified in this strange way. The `-n` indicates that the name of the location this file is executed in should be the CWD, not and empty one, and the `-i` indicates that variables previously defined should be accessible to the script (run like a script, not a function).

In [30]:
%run -n -i "SubFolder_for_Testing_CWD/Testing_CWD.py"
print(os.getcwd())
os.chdir(path)
print(os.getcwd())

/Users/alexanderbrandon-bravo/OneDrive/Documents/Paris - CRI/Early Learning
/Users/alexanderbrandon-bravo/OneDrive/Documents
/Users/alexanderbrandon-bravo/OneDrive/Documents
/Users/alexanderbrandon-bravo/OneDrive/Documents/Paris - CRI/Early Learning


The change to the CWD is carried through whether the file is run directly as a script, or imported and a function run from it.

The code in the function here is the same as the script except it backs up only one folder.

In [31]:
import Testing_CWD_importing_functions

In [34]:
Testing_CWD_importing_functions.test()
print(os.getcwd())
os.chdir(path)
print(os.getcwd())

/Users/alexanderbrandon-bravo/OneDrive/Documents/Paris - CRI/Early Learning
/Users/alexanderbrandon-bravo/OneDrive/Documents/Paris - CRI
/Users/alexanderbrandon-bravo/OneDrive/Documents/Paris - CRI
/Users/alexanderbrandon-bravo/OneDrive/Documents/Paris - CRI/Early Learning


## Creating and deleting folders

If tmp does not already exist, this will fail.
If a new folder in the current working directory is required, no slashes are necessary.
eg `path = "tmp"`

In [12]:
# define the name of the directory to be created

path = "tmp/tmp2"

try:
    os.mkdir(path)
except OSError:
    print ("Creation of the directory %s failed" % path)
else:
    print ("Successfully created the directory %s " % path)

Successfully created the directory tmp/tmp2 


To create multiple directories, use:

In [16]:
# define the name of the directory to be created
path = "Multiple/at/once"

try:
    os.makedirs(path)
except OSError:
    print ("Creation of the directory %s failed" % path)
else:
    print ("Successfully created the directory %s" % path)

Successfully created the directory Multiple/at/once


You can actually use this generally as it is possible to create one extra folder within a set of already created folders:

In [17]:
# define the name of the directory to be created
path = "Multiple/at/once/again"

try:
    os.makedirs(path)
except OSError:
    print ("Creation of the directory %s failed" % path)
else:
    print ("Successfully created the directory %s" % path)

Successfully created the directory Multiple/at/once/again


The below demonstrates both a temporary file, which is automatically put into a temporary directory of default name, as well as the utility of the with statement. The point is the with statement defines, temporarily, some quantities, which are forgotten once the indented section is executed.

In [18]:
import tempfile

# create a temporary directory
with tempfile.TemporaryDirectory() as directory:
    print('The created temporary directory is %s' % directory)

# directory and its contents have been removed by this point

The created temporary directory is /var/folders/qc/fg6mhgbd5ld9fy106vr34fn00000gp/T/tmpi24yxmdy


`rmdir()` requires a path string that contains the directory name, and only deletes the deepest entry in the path string. Note that this only works when the directory is entirely empty. If it is not empty then an `OSError` is raised. 

In [19]:
path = "/Users/alexanderbrandon-bravo/Desktop/Test_Folder/Multiple/at/once/again"

try:
    os.rmdir(path)
except OSError:
    print ("Deletion of the directory %s failed" % path)
else:
    print ("Successfully deleted the directory %s" % path)

Successfully deleted the directory /Users/alexanderbrandon-bravo/Desktop/Test_Folder/Multiple/at/once/again


Notice the use of the full directory here. This is triggered to be the case by opening the string with a `/`. Alternatively, something like the following would also have been valid:

In [51]:
path = "tmp/tmp2"

try:
    os.rmdir(path)
except OSError:
    print ("Deletion of the directory %s failed" % path)
else:
    print ("Successfully deleted the directory %s" % path)

Successfully deleted the directory tmp/tmp2


For some reason, subsequently deleting the parent folder fails....

In [52]:
path = "tmp"

try:
    os.rmdir(path)
except OSError:
    print("Deletion of the directory %s failed" % path)
else:
    print("Successfully deleted the directory %s" % path)

Deletion of the directory tmp failed


Additionally,

`os.remove()` removes a file.

`shutil.rmtree()` deletes a directory and all its contents. and will delete more than just the deepest entry in the path string.

In [53]:
import shutil

In [54]:
path = "tmp"

try:
    shutil.rmtree(path)
except OSError:
    print("Deletion of the directory %s failed" % path)
else:
    print("Successfully deleted the directory %s" % path)

Successfully deleted the directory tmp


## Checking if folders/files exist

To check if the object exists, regardless of type, use:

In [8]:
print(os.path.exists('SubFolder_for_Testing_CWD'))
print(os.path.exists('Testing_CWD_importing_functions.py'))
print(os.path.exists('../Admin'))
print(os.path.exists('../Admi'))

True
True
True
False


To check specifically if it is a folder use:

In [6]:
print(os.path.isdir('SubFolder_for_Testing_CWD'))
print(os.path.isdir('Testing_CWD_importing_functions.py'))

True
False


Likewise, to check specifically if a file exists, use:

In [7]:
print(os.path.isfile('SubFolder_for_Testing_CWD'))
print(os.path.isfile('Testing_CWD_importing_functions.py'))

False
True
